name: Build and deploy
on:
  push: {}
jobs:
  build-preview-system:
    runs-on: ubuntu-20.04
    name: Build PreviewSystem project
    steps:
    - uses: actions/checkout@v3
    - name: Build PreviewSystem
      run: ./PreviewSystem/build-script.sh
    - name: Upload PreviewSystem artifact
      uses: actions/upload-artifact@v2
      with:
        name: PreviewSystem
        path: PreviewSystem/distribution
  build:
    runs-on: macOS-latest
    name: Build frontend project
    needs: [build-preview-system]
    steps:
    - uses: actions/checkout@v3
    - name: Select latest Xcode
      run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app/Contents/Developer/
    - uses: actions/download-artifact@v2
      with:
        name: PreviewSystem
        path: PreviewSystem/distribution
    - name: Build Frontend
      working-directory: Frontend
      run: |
        brew install wabt binaryen
        npm install
        npm run build:prod
    - name: Upload Frontend artifact
      uses: actions/upload-artifact@v2
      with:
        name: Frontend
        path: Frontend/dist
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    name: Deploy artifacts
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Download Frontend artifact
      uses: actions/download-artifact@v2
      with:
        name: Frontend
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
  build-frontend-docker-image:
    runs-on: ubuntu-latest
    name: Build Frontend Docker image
    steps:
    - uses: actions/checkout@v3
    - name: Build Frontend image
      run: docker build -f docker/Frontend/Dockerfile .
  build-compile-api-docker-image:
    runs-on: ubuntu-latest
    needs: [build-preview-system]
    name: Build CompileAPI Docker image
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v2
      with:
        name: PreviewSystem
        path: PreviewSystem/distribution
    - uses: docker/setup-buildx-action@v2
    - name: Build CompileAPI image
      run: docker buildx build -f docker/CompileAPI/Dockerfile .
